cc_test(
    name = "message_queue_test",
    srcs = ["message_queue_test.cpp"],
    deps = [
        "//src/message_queue",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "processor_test",
    srcs = ["processor_test.cpp"],
    deps = [
        "//src/message_queue",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "stage_test",
    srcs = ["stage_test.cpp"],
    deps = [
        "//src/message_queue",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
